# Generated by Django 3.0.3 on 2020-05-20 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_SMP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='students_attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Attendance_status', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], max_length=1)),
                ('Reason', models.CharField(blank=True, max_length=50, null=True)),
                ('attendance_date', models.DateField()),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_SMP.Student_List')),
            ],
        ),
    ]
